<?php
	$aFeedNames = $aFeedNames;

	if (!empty($aQueueData)) {
		$aFeedParameters = unserialize($aQueueData['parameters']);
		$sFeedName = $aSingleFeed['feed_name'];

	}
?>

	<div class="cDivFormContainer">
		<?php // echo $oForm; ?>
        <p>
            <div class="cDivElementContainer">
                <label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Title:' ); ?></label> 
                <input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php echo esc_attr( $instance['title'] ); ?>" />
            </div>
        </p>
		<div class="cDivElementContainer">

			<select name="<?php echo $this->get_field_name('selectFeedName');?>" class="cSelectFeedName">
				<?php if (empty($aQueueData)) { ?>
					<option value="0" selected="">Select Data Feed</option>

					<?php foreach ($aFeedNames as $aFeed) { ?>

					<option value="<?php echo $aFeed['feed_slug']; ?>" > <?php echo $aFeed['feed_name']; ?> </option>

					<?php } ?>

				<?php } else { ?>
					<option value="0" >Select Data Feed</option>

					<?php foreach ($aFeedNames as $aFeed) { ?>

					<option value="<?php echo $aFeed['feed_slug']; ?>" <?php echo ($aFeed['feed_name'] === $sFeedName) ? 'selected' : '';?> > <?php echo $aFeed['feed_name']; ?> </option>

					<?php }?>


				<?php }?>

			</select>


		</div>

		<div class="cDivAjaxReturnJDWidget">
			<?php
				if (!empty($aQueueData)) {
					$iQueueId = $aQueueData['id'];
					$iFeedDataId = $aQueueData['json_data_id'];
					foreach ($aFeedParameters as $sFeedName => $sDefaultValue) { ?>
						<p>
						<div class="cDivElementContainer">
							<label><?php echo ucfirst($sFeedName); ?>:</label><br/>
							<input type="text" name="<?php echo $this->get_field_name($sFeedName); ?>" value="<?php echo $sDefaultValue;?>" class="widefat">
						</div>
						</p>

				<?php	} //end of for each ?>

					<input type="hidden" name="<?php echo $this->get_field_name('hiddenFeedId')?>" value="<?php echo $iFeedDataId; ?>">
					<input type="hidden" name="<?php echo $this->get_field_name('hiddenQueueId')?>" value="<?php echo $iQueueId; ?>">

			<?php } ?>
		</div>

	</div>

	<div class="cDivAjaxLoader">
		<img class="cImageAjaxLoader" src="<?php echo JsonData_Plugin_Url;?>/assets/img/ajax-loader.gif" style="display: none;"/>
	</div>



