<?php include JsonData_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>
<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-cog"></i>&nbsp;Settings</h2>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<div id="iDivResponseContainer"></div>
		</div>
	</div>


	<div class="row-fluid">
		<?php echo $aContent['form']; ?>
	</div>
</div>