# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "homepage-20151222"
    config.vm.box_url = "http://files.support.akvo-ops.org/homepage-dev-20151222.box"
    config.vm.synced_folder "../", "/vagrant/homepage/checkout/", id: "code-root",
      :owner => "homepage",
      :group => "www-data",
      :mount_options => ["dmode=775", "fmode=664"]
     
    config.vm.network :private_network, ip: "192.168.50.101"

    config.vm.provision "shell", path: "./provisioning/link_code.sh"
    config.vm.provision "shell", path: "./provisioning/prepare_test_db.sh"
    config.vm.provision "shell", run: "always", path: "./provisioning/fix_dns.sh"

end

