# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "homepage-20151027"
    config.vm.box_url = "http://files.support.akvo-ops.org/homepage-dev-20151027.box"
    config.vm.synced_folder "../", "/vagrant/homepage/checkout/", id: "code-root",
      :owner => "homepage",
      :group => "www-data",
      :mount_options => ["dmode=775", "fmode=664"]
     
    config.vm.network :private_network, ip: "192.168.50.101"

    config.vm.provision :shell, :path => "./provision_vagrant.sh"

end

