<?php
/*
	Template Name: staffDescr
*/
?>
<div class="extLoad" id="peter">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/peter_240.jpg" title="Peter Van Der Linde" Alt="Peter Van Der Linde - Co-founder and co-director" /></div>
  <h1>Peter Van Der Linde</h1>
  <p class="staffTitle">Co-founder and co-director</p>
 <p class="staffBio"><br/><br/>Peter is a co-founder of Akvo and has directed partner relationships since autumn 2006. Combining considerable field experience with a large contact network, he is a 'connector' between governmental organisations, corporates, NGOs and knowledge institutes. <br/><br/>Peter leads Akvo's funding and implementation deals with international development institutions, banks, companies, implementation NGOs and other investors. He ensures that Akvo's first tools meet the needs of our initial investor and implementation NGO partners. <br/><br/>Previously a programme manager at the Netherlands Water Partnership (NWP), he combines technical knowledge of water management with the ability to mobilise an extensive, high level network of water and sanitation changemakers across the world. Hehas an MSc in integrated water management and disaster studies from Wageningen University. Follow Peter on Twitter <a href="//www.twitter.com/petervdl">@petervdl</a>.
 </p>
 </div>
<div class="extLoad" id="kathelyne">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/kathelyne240x135.png" title="Kathelyne van den Berg" Alt="Kathelyne van den Berg, Chief financial officer" /></div>
  <h1>Kathelyne van den Berg</h1>
  <p class="staffTitle">Chief financial officer</p>
  <p class="staffBio"><br/><br/>Kathelyne devises and manages Akvo’s financial and operational processes and contributes substantially to strategic planning. She also leads our participation in the Connect4Change consortium and other Akvo partner programmes including Mars. She has a background in the supervision and auditing of water management programmes.
<br/><br/> Before joining Akvo, Kathelyne was an inspector and auditor at the Inspectorate Transport and Water Management (IVW) where she analysed results and informed and advised policymakers and adminstrators in central government. She has an MSc and BSc in International Land and Water Management from Wageningen University and has worked on awareness-raising around irrigation and watershed management in field situations in Peru, Bangladesh and Jordan.
<br/> You can find her on Twitter <a href="//www.twitter.com/kathelyne">@kathelyne</a> and she's based in our Amsterdam office. </p></div>
<div class="extLoad" id="luuk">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Luukv2.jpg" title="Luuk Diphoorn" Alt="Luuk Diphoorn, manager, East Africa hub " /></div>
  <h1>Luuk Diphoorn</h1>
  <p class="staffTitle">Manager, East Africa hub</p>
 <p class="staffBio"><br/><br/> Luuk leads Akvo's project activities with our NGO partners in East Africa and steers the expansion of our new hub at the NaiLab in Nairobi, Kenya. This includes identifying appropriate projects to upload to the Akvo system, gathering the relevant content from each organisation and training teams on how to share regular updates.<br/><br/> He is also a lead producer and reporter for WaterCube, our video channel profiling people and issues in the water and sanitation sector. Luuk graduated in 2007 with an MA in International Development Studies from the University of Utrecht. Having grown up in Burundi, Burkina Faso, Sri Lanka and Bangladesh, he has worked on several international development programmes including the World Water Dome in Johannesburg (2002) and a project to assess environmental impact at the IWMI in Colombo in Sri Lanka (06/07). You can find Luuk on Twitter at: <a href="//www.twitter.com/luukdiphoorn">@luukdiphoorn</a></p></div>
<div class="extLoad" id="markW">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/mtw1.jpg" title="Mark Tiele Westra" Alt="Mark Tiele Westra, Akvopedia editor and programme manager " /></div>
  <h1>Mark Tiele Westra</h1>
  <p class="staffTitle">Akvopedia editor and programme manager</p>
 <p class="staffBio"><br/><br/>Mark maintains the high quality standards of Akvopedia and organises the online community which feeds it, adding and improving content and helping others do the same. He also leads Akvo's role in the WASH Consortium and is a key member of the team developing and deploying Akvo FLOW. <br/><br/>He combines technical knowledge on sustainable, simple water technology with broad technical editorial experience. <br/><br/>Studying physics and philosophy of technology at Technical University of Twente, he holds a PhD in physics from the Eindhoven Technical University. Previously head of communication of a Dutch scientific institute working on nuclear fusion, he also led communications for the European Fusion programme and international fusion experiment, ITER. On the Working Group on Development Techniques (WOT), at University of Twente, he develops and disseminates knowledge of simple technology for using wind, water and solar power in developing countries. He has conducted technical training on rope pumps in Nicaragua and Tanzania. He joined Akvo at the end of 2008. Mark talks more about his role in this video interview. Follow him on Twitter <a href="//www.twitter.com/mtwestra">@mtwestra</a>.</p></div>
<div class="extLoad" id="jeroen">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/jvds_240.jpg" title=" Jeroen van der Sommen" Alt="Jeroen van der Sommen, co-founder " /></div>
  <h1>Jeroen van der Sommen</h1>
  <p class="staffTitle">Co-founder</p>
  <p class="staffBio"><br/><br/>Jeroen is responsible for developing and maintaining Akvo’s relationships with all types of partner organisations, with a particular focus on Europe and Africa. He works to achieve a balance in Akvo’s international activities, ensuring support is available for partners in countries where it’s needed. Until March 2012, he was chairman of Akvo’s board.
<br/><br/>
Jeroen ignited the Akvo phenomenon after meeting Thomas Bjelkeman at Stockholm World Water Week in summer 2006 and has steered Akvo’s evolution to ensure it is relevant to, and supported by, a wide range of implementation NGOs, funding partners and global institutions. He started his career as a geologist in Burkina Faso in 1982 and holds an MSc. in Hydrology from Vrije Universiteit Amsterdam. He worked throughout the 1980s in countries such as Burkina Faso, Mozambique, Niger, Mali, Indonesia and India, managing water supply and management projects on behalf of organisations such as the World Bank and the European Union. In 1998, Jeroen founded the Netherlands Water Partnership, where he built a dynamic network of over 200 member organisations that collaborate.</p></div>
<div class="extLoad" id="frodo">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/frodoprofilepicx240.jpg" title="Frodo van Oostveen" Alt="Frodo van Oostveen, programme manager" /></div>
  <h1>Frodo van Oostveen</h1>
  <p class="staffTitle">Programme manager </p>
  <p class="staffBio"><br/><br/>Frodo runs Akvo's relationships with corporate and foundation partners, including business and consumer brands. He has extensive experience as a project manager in events, public affairs, marketing and communication. He worked at ABN AMRO bank for seven years. He was public relations and event manager for Team ABN AMRO in the Volvo Ocean Race, where he managed non-stop, for 11 months, marketing and events at each port of call on the 2005/6 race, and was corporate hospitality manager the following year.<br/><br/> He later became a business manager in ABN AMRO's global public affairs team, reviewing sponsorship and stakeholder partnerships and developing new sports-related initiatives. In 2010 he joined the Netherlands Water Partnership as senior program manager, Water, Sanitation and Hygiene, developing "Water2020", a strategic vision for the Dutch water sector. He has an MBA from Radboud University Nijmegen. His bachelors degree is in Marketing and Commercial Economics from Tilburg University, where he majored in sports marketing and management. In 2008 Frodo was nominated and selected as "Young Professional of the Year" in the Netherlands (Volkskrant). Follow Frodo on Twitter <a href="//www.twitter.com/frodo1977">@frodo1977</a>. </p></div>
<div class="extLoad" id="amit">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/amit240.jpg" title="Amitangshu Acharya" Alt="Amitangshu Acharya, Programme Manager, Asia Hub" /></div>
  <h1>Amitangshu Acharya</h1>
  <p class="staffTitle">Programme Manager, Asia Hub</p>
  <p class="staffBio"><br/><br/>Amitangshu combines an extensive academic background with hands-on experience managing development projects at field level. He has a Master of Science in Environment, Culture and Society (with Distinction) from the University of Edinburgh, UK, and a Master of Arts in Social Work from Tata Institute of Social Sciences in Mumbai, India.<br/><br/> Prior to his MSc he worked as a project officer for Arghyam, the highly-regarded Indian development organisation focused on water and sanitation. Here he selected, coordinated and evaluated water, sanitation and hygiene projects across nine states in India. He was a programme associate of the National Resource Management Division of Winrock International India (WII) where he worked on issues including agricultural pollution, urban wastewater, landscape and livelihood, and ecosystem services. He also worked as a project officer for a UNDP and MoRD project facilitating women's group formation and forest and common land management committees. He is based in Delhi. </p></div>
<div class="extLoad" id="hans">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/hans240.jpg" title="Hans Merton" Alt="Hans Merton, project manager" /></div>
  <h1>Hans Merton</h1>
  <p class="staffTitle">Project manager</p>
  <p class="staffBio"><br/><br/>Hans helps establish new programmes and consortia so partners can unleash the potential of Akvo RSR, Akvo FLOW, Akvopedia and Akvo Openaid. Hans has twenty years experience as a manager and director of programmes and divisions in the field of environmental and water management consultancy.<br/><br/> Before joining Akvo he was a director of corporate marketing and communications and deputy director of the Environment division at Royal Haskoning. One of Europe's top project management, engineering and consultancy groups, it is the oldest consultancy firm in the Netherlands, established in 1881. As a management consultant at the firm Proven Partners, he worked for several years on knowledge management initiatives. Hans studied civil engineering, water management and sanitation as a geohydrologist at TU Delft, including a period in Burkina Faso. From University, he joined Iwaco BV as a researcher, then project manager and later regional director, leading teams focused on water management and soil & groundwater quality. He is based in the Netherlands. </p></div>
<div class="extLoad" id="phylis">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/phylis2_240b.jpg" title="Phylis Gichuru Webi" Alt="Phylis Gichuru Webi, partnerships assistant, East Africa hub " /></div>
  <h1>Phylis Gichuru Webi</h1>
  <p class="staffTitle">Partnerships assistant, East Africa hub </p>
 <p class="staffBio"><br/><br/> Phylis is responsible for assisting with project activities for our partners in East Africa. In this role, Phylis helps train local partners on Akvo RSR and works with partners to create and update projects online. Phylis also identifies projects and organisations to partner with and assists in the administrative operations of the Akvo office at the NaiLab in Nairobi, Kenya.
  <br/><br/>Prior to joining Akvo, Phylis worked as a procurement assistant for the Mavuno Church, Nairobi Chapel, where she had a range of procurement and finance responsibilities. She has also previously held customer service and sales roles and has studied information technology at the InfoTech Training Center and the Institute of Advanced Technology. Phylis holds a diploma in Business Administration from the University of Nairobi and is currently pursuing a bachelors degree in Business Management from Kenya Methodist University. Follow Phylis on Twitter <a href="//www.twitter.com/PhylisWebi">@PhylisWebi</a></p></div>
<div class="extLoad" id="laura">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/laura240.jpg" title=" Laura Roverts" Alt=" Laura Roverts, project officer " /></div>
  <h1>Laura Roverts</h1>
  <p class="staffTitle">Project manager</p>
  <p class="staffBio"><br/><br/>Laura has master and bachelor's degrees in International Development Studies from Wageningen University. She's worked as a researcher in the department of San Marcos, Guatemala, studying living with risk of natural disaster, where she also studied Spanish.<br/><br/> In Sierra Leone, she worked with iEARN, a local NGO assisting former child soldiers and amputees. There she conducted interviews and made documentaries, and supported reintegration programmes such as computer classes and music, theatre and assertiveness workshops. Recently she has worked as a programme coordinator at Ayni Bolivia, a Bolivian NGO focused on poverty reduction and equality, and was an assistant at the Municipal of Utrecht's naturalisation office. She was a finalist in the Vodafone World of Difference 2010 competition. She's on Twitter <a href="//www.twitter.com/lauraroverts">@lauraroverts</a>.</p> </div>
<div class="extLoad" id="lissy">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/lissy240.jpg" title="Lissy van Noort" Alt="Lissy van Noort, project officer" /></div>
  <h1>Lissy van Noort</h1>
  <p class="staffTitle">Project officer</p>
 <p class="staffBio"><br/><br/> Lissy helps coordinate the partner team's events activity, ranging from international development conferences to the more quirky and interesting opportunities we encounter. She also helps manage the portfolio of projects that Akvo is bringing online with the Connect4Change consortium. Lissy joined Akvo at the end of 2011, having recently completed a masters degree in Socialisation and Youth Policies at Utrecht University, where she majored in Education, Youth and International Cooperation and Aid. She's spent time conducting local research In Uganda on parental participation in education and has worked for NGOs including SNV Uganda and Edukans. She also worked at our neighbours, the 1%CLUB. Follow Lissy on Twitter <a href="//www.twitter.com/lissyvn">@lissyvn</a>.</p></div>
<div  class="extLoad" id="francis">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/francis240.png" title="Francis Warui" Alt="Francis Warui, partnership assistant, East Africa hub" /></div>
  <h1>Francis Warui</h1>
  <p class="staffTitle">Partnership assistant, East Africa hub</p>
 <p class="staffBio"><br/><br/> Francis provides training and technical support to Akvo's NGO partners in East Africa. He has seven years' experience in the field of geographical information systems (GIS) and data management. Before joining Akvo he was a geo consultant at Upande Ltd in Nairobi, where he was part of the team that developed the VirtualKenya GIS portal. He also conducted spatial data collection (using Akvo FLOW and other tools) and provided training and technical support to Kenyan water point mapping teams.<br/><br/> Prior to that he helped to develop data systems for the Kenya Medical Research Institute (KEMRI) and the International Livestock Research Institute (ILRI), Nairobi. As a student associate at ILRI, he was trained to work with communities in resource mapping and teaching community members practical skills related to GPS, data and GIS analysis. He has a Diploma in Information Studies and a Higher National Diploma in Library and Information Management from the Kenya Polytechnic University College, as well as an Undergraduate Diploma in Geo-informatics (with distinction) from the University of Twente. He speaks English, Swahili and Kikuyu. Follow Francis on Twitter <a href="//www.twitter.com/fnwarui">@fnwarui</a>.</p></div>
<div class="extLoad" id="henry">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/henry240.jpg" title="Henry Jewell" Alt=" Henry Jewell, Executive director, Akvo Foundation USA and programme manager, Akvo FLOW" /></div>
  <h1>Henry Jewell</h1>
  <p class="staffTitle">Executive director, Akvo Foundation USA and programme manager, Akvo FLOW</p>
 <p class="staffBio"><br/><br/> As executive director of Akvo Foundation USA, Henry is responsible for growing Akvo's presence in the US. Henry is also the programme manager for Akvo FLOW and is responsible for FLOW partner support, providing technical support to current users and helping us understand current and future user needs. Henry joined Akvo from the World Bank where he was a geospatial analyst overseeing R & D and implementation of Geographical Information Systems (GIS) techniques within World Bank studies and programmes.
<br/><br/>
Henry's been passionate for all things geographic ever since his childhood on a farm in England. This led to many adventures on geography field trips and finally to a BSc in Marine Geography from Cardiff University and an MA in Geography from the George Washington University, where he wrote his thesis on using GIS and remotely sensed data to map variabilities in health and wealth outcomes in the neighbourhoods of Accra, Ghana. Between academic tours he worked for South African National Parks as a Social Ecologist and did a stint at Foxtons in London (complete with his own Mini). Henry loves being outdoors, running and reading.</p></div>
<div class="extLoad" id="joyce">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/joyce240.jpg" title="Joyce Kent" Alt="Joyce Kent, office manager " /></div>
  <h1>Joyce Kent</h1>
  <p class="staffTitle">Office manager</p>
  <p class="staffBio"><br/><br/>Joyce is responsible for the day to day operations of the Akvo office in Amsterdam, including administration, human resources, facilities management and making it look gorgeous. <br/><br/>She also supports the Akvo team on event planning. Prior to joining Akvo, Joyce worked in a range of roles helping international organisations set up local offices in Amsterdam. She also started a production company where she honed her experience in project, event and office management. Joyce studied Psychology at the University of Amsterdam. </p></div>
<div class="extLoad" id="josje">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/josje240.jpg" title="Josje Spierings" Alt="Josje Spierings, project coordinator" /></div>
  <h1>Josje Spierings</h1>
  <p class="staffTitle">Project coordinator</p>
  Josje supports Akvo's involvement in events such as the Open Data Development Camp and works one day a week on events for <a href="//openforchange.info">Open for Change </a>, an open development network of which Akvo is a founding partner. She is also responsible for partnerships connected to Akvo’s OpenAid product. Prior to joining Akvo, Josje was an assistant project manager at Akvo's partner the 1%CLUB, where she helped coach project owners, organise events such as the 1%EVENT and 24 Hour Action and foster relationships with partners.<br/><br/> She has also volunteered at the Dutch Council for Refugees, where she helped refugees learn Dutch and prepare for their Dutch integration course. Josje has a BA in Cultural Anthropology and Development Sociology and a BSc in Public Administration from Leiden University. Follow her on Twitter <a href="//www.twitter.com/JosjeSpierings">@JosjeSpierings</a>.</div>
<div class="extLoad" id="annaM">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Annamarthe240.jpg" title="Anna-Marthe Sessink" Alt=" Anna-Marthe Sessink, project coordinator" /></div>
  <h1>Anna-Marthe Sessink</h1>
  <p class="staffTitle">Project coordinator </p>
 <p class="staffBio"><br/><br/> Anna-Marthe assists the team in building and maintaining partnerships, as well as helping organise Akvo’s participation in events such as De Parade. Prior to joining Akvo, she held an internship in marketing and communications at Rabobank. Anna-Marthe is currently studying business administration at the Rotterdam School of Management, Erasmus University. <br/><br/>During the course of her studies, she has worked on research projects on the potential of social media within Dutch aid and development organisations and conducted field research in Kenya to develop a business plan for a secondary school for underprivileged girls in Kenya. She has also participated in Business Administration exchange programmes in Lethbridge, Canada and Bangkok, Thailand and attended an international Intensive Programme in Torun, Poland.</p> </div>
<div class="extLoad" id="charlotte">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/charlotte240.jpg"  title="Charlotte Soedjak" Alt="Charlotte Soedjak, project officer" /></div>
  <h1>Charlotte Soedjak</h1>
  <p class="staffTitle">Project officer</p>
 <p class="staffBio"><br/><br/> Charlotte works across a range of our partner programmes and helps to develop and co-ordinate our training and support tools, workshops and evaluation. Her masters degree in Tourism and Environment with International Development from Wageningen University took her to Indonesia to write a thesis on stakeholders' perspectives on tourism in Wakatobi. <br/><br/>While there she studied Indonesian as well as volunteering to teach English. She also has a BA in Facility Management from Diedenoort University. Before moving into the development sector, Charlotte worked in a variety of facilities management and communications roles in Australia and the Netherlands. In her spare time, Charlotte has worked as an ambassador for Travel Active, leading workshops and information sessions for students and parents. Follow Charlotte on Twitter <a href="//www.twitter.com/charlottesoed">@charlottesoed</a>. </p></div>
<div class="extLoad" id="markC">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/charmerx2240.jpg" title="Mark Charmer" Alt="Mark Charmer, co-founder and communications director" /></div>
  <h1>Mark Charmer</h1>
  <p class="staffTitle">Co-founder and communications director </p>
  <p class="staffBio"><br/><br/>Mark joined Akvo in autumn 2006 and directs its communications. Akvo has a unique opportunity to talk more openly and directly than previous development sector projects. He ensures we tell the Akvo story in a discoverable way, inspiring audiences while managing expectations. He also improves how we describe ourselves to key groups. Mark is the producer of WaterCube.tv, our unique video channel profiling people and issues in international development. <br/><br/>Mark has a Masters degree in Design from Central St Martins College and a BSc in Managerial and Administrative Studies from Aston University. He brings 18 years experience running international communications for companies such as HP, Compaq, Dell and Apple and was a senior advisor to world top 3 PR agency Hill & Knowlton for eight years. He is managing director of The Movement Design Bureau, a think tank that researches advanced design related to cities, mobility, development and collaboration. He is based in London. Follow Mark on Twitter <a href="//www.twitter.com/charmermark">@charmermark</a>.</p> </div>
<div class="extLoad" id="jo">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/jocrop240.png" title="Jo Pratt" Alt=" Jo Pratt, communications manager " /></div>
  <h1>Jo Pratt</h1>
  <p class="staffTitle">Communications manager</p>
<p class="staffBio"><br/><br/>  Jo has worked in marketing and communications in both the IT and non-profit sectors. For seven years, she was at Firefly Communications, a highly-regarded British technology PR agency. At Firefly she represented clients including COLT Telecom, The Core Trust, FT.com, Lucent Technology, Reuters Business Information, Sequent, TDK, Vodafone and the World Internet Forum. She later helped to lead the company's expansion into Europe, establishing its French and German operations. Jo then moved into the charity sector, initially focusing on fair trade. <br/><br/>She was PR manager at People Tree, a fair trade and ecological fashion company, and also worked for Cafédirect and the Fairtrade Foundation. Following this she moved to national hospice charity Help the Hospices for five years, conducting marketing and PR related to its UK and international work, as well as acting as a consultant to local hospices. Her current focus at Akvo is on aspects of communication related to Akvo RSR and Openaid. Jo has a BA in French and Russian from the University of Nottingham. Follow Jo on Twitter <a href="//www.twitter.com/jo108">@jo108</a>. </p></div>
<div class="extLoad" id="emily">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Emily240.jpg" title="Emily Armanetti" Alt="Emily Armanetti, communications manager" /></div>
  <h1>Emily Armanetti</h1>
  <p class="staffTitle">Communications manager</p>
  <p class="staffBio"><br/><br/>Emily is a communications consultant, supporting the Akvo team. She has worked in technology communications for more than 13 years. During this time, Emily has worked on a diverse mix of business and consumer technology campaigns for multi-national brands. After three years at a specialist technology public relations agency, Emily joined global communications consultancy Hill and Knowlton, where she managed local, regional and global campaigns for organisations such as HP, Intel and Motorola.<br/><br/> After four years in the company’s Chicago office, Emily relocated to Hill and Knowlton London where she expanded her role to include campaigns in Europe, Middle East and Africa and gained invaluable experience in cross-cultural communication. Following this, Emily spent two years at Nokia where she managed communications for the company’s music and fashion handsets. Emily has a BA in Journalism from Indiana University. She is based in Brooklyn, NY. You can find her on Twitter <a href="//www.twitter.com/earmanetti">@earmanetti</a>.</p> </div>
<div class="extLoad" id="linda">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Linda240.jpg" title="Linda Leunissen, illustrator and graphic designer" Alt="Linda Leunissen, illustrator and graphic designer" /></div>
  <h1>Linda Leunissen</h1>
  <p class="staffTitle">Illustrator and graphic designer </p>
 <p class="staffBio"><br/><br/> Linda is responsible for helping tell Akvo’s story visually. In this role, she lends her graphic design skills to many areas of the company, contributing to training materials, presentations, press materials and grant proposals. Inspired by her love of fairy tales and stories, Linda creates designs in which small stories are hidden. Prior to joining Akvo, Linda worked as a consultant for Artamuse, where she developed lesson projects about audio-visual arts for elementary schools. <br/><br/>She also worked as a graphic designer and PR and marketing manager for ZZDP Architecten. Linda’s passion for interpretive designs and cultural heritage has led her to volunteer her time and expertise to organisations such as Centraal Museum, NorthernLight, and CODA Museum. She has also volunteered as a teacher of fine arts and cultural heritage at a number of schools in the Netherlands. Linda has a BA in Cultural Heritage from Reinwardt Academy in Amsterdam and a BA in Fine Arts in Education from the Academy of Fine Arts in Maastricht, the Netherlands. In addition to working for Akvo, she also makes narrative graphic designs for Dutches, her own studio. She is based in London. You can find her on Twitter @StudioDutches.</p> </div>
<div class="extLoad" id="thomas">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/thomas_240.jpg" title="Thomas Bjelkeman-Pettersson" Alt="Thomas Bjelkeman-Pettersson: co-founder and co-director" /></div>
  <h1>Thomas Bjelkeman-Pettersson</h1>
  <p class="staffTitle">Co-founder and co-director </p>
 <p class="staffBio"><br/><br/> Thomas is a visionary systems architect and designer with both a software and environmental science background. He is our chief technology officer and steers the team to harness the maximum potential from open source methods. He began developing software ventures in Britain and California, working closely with many early-wave internet entrepreneurs.<br/><br/> A serial entrepreneur himself, he helped introduce web technology in corporate environments during the mid-nineties. In 1994, he helped start Stellent CMS which eventually sold to Oracle. In 1997 he co-founded web analytics company ISSEL and in 1999 Zezame, which built web page annotation systems. Since 2004 Thomas has helped develop the Seawater Greenhouse, a revolutionary food production system for arid coastal regions. An advisory board member of the India Water Portal, he’s currently completing an MSc in Environmental Science at Stockholm University. Follow Thomas on Twitter <a href="//www.twitter.com/bjelkeman">@bjelkeman</a>. </p></div>
<div class="extLoad" id="paul">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Paul240.jpg" title="Paul Burt: web programmer" Alt="Paul Burt: web programmer" /></div>
  <h1>Paul Burt</h1>
  <p class="staffTitle">Web programmer</p>
  <p class="staffBio"><br/><br/>Paul writes code for the back-end of the Akvo system - the software that affects how things work, as opposed to how they look. He worked in systems admin and customer support roles before moving into Django and Python-based web development. <br/><br/>Paul helps out with Akvo server infrastructure and has been working on our PayPal donation engine that takes and processes project donations through the site. Paul has worked in engineering and support roles for Adobe, Autodesk, the Flanders Institute for Biotechnology and the Information Security Group. He has a BA in Dutch from University College London. You can find Paul on Twitter <a href="//www.twitter.com/pycurious">@pycurious</a>.</p> </div>
<div class="extLoad" id="oli">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/oligl.png" title="Oliver Galloway-Lunn" Alt="Oliver Galloway-Lunn, Developer" /></div>
  <h1>Oliver Galloway-Lunn</h1>
  <p class="staffTitle">Developer</p>
  <p class="staffBio"><br/><br/>Oliver builds the automated testing and release management tools that help the Akvo team maintain its software release schedule, so we can add new features to the system on a very frequent basis.<br/><br/> Oliver has worked as a senior analyst developer in several major financial services firms, including BlueCrest Capital Management and Morgan Stanley, where he helped teams develop software that was more agile, higher quality and cheaper to implement. Recently he's also developed a number of iPhone apps. Oliver graduated in computer science and psychology at the University of Witwatersrand and has worked since as helpdesk manager, software developer and analyst. He lives in London. You can find him on Twitter at: <a href="//www.twitter.com/olixx">@olixx</a></p></div>
<div class="extLoad" id="loic">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/loic240.jpg" title="Loïc Sans" Alt="Loïc Sans, designer and front-end developer" /></div>
  <h1>Loïc Sans</h1>
  <p class="staffTitle">Designer and front-end developer</p>
  <p class="staffBio"><br/><br/>Loïc is responsible for web design and front-end user interface for Akvo. Prior to joining Akvo, Loïc was head of design at Arkkeo Oy, where he developed their user interface, and was also involved in user experience analysis, marketing and business strategy.<br/><br/> Prior to that, Loïc was the head of design for blinkbox, the first independent on-demand movie and television streaming service in the UK. Having joined at the inception of the company, he created the company’s visual identity and branding, as well as the first version of the website and video player. Loïc has also worked as a freelance illustrator and web designer for a diverse range of clients including photographers, fashion designers, architects and musicians. Loïc has a degree in Illustration and Computer Graphics from the Conservatoire Nationale des Arts et Métiers in Paris and a DEUG from the University of Bordeaux. He is based in Helsinki. You can find Loïc on Twitter at: <a href="//www.twitter.com/loicsans">@loicsans</a></p></div>
<div class="extLoad" id="gabriel">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/gabriel_240.jpg" title="Gabriel von Heijne" Alt="Gabriel von Heijne, co-founder and developer" /></div>
  <h1>Gabriel von Heijne</h1>
  <p class="staffTitle">Co-founder and developer </p>
 <p class="staffBio"><br/><br/> Gabriel has been an independent software developer for 15 years. He works primarily in Python, the programming language upon which Akvo RSR is built, along with the website framework Django. Gabriel also leads the development and management of Akvo's web servers based on Linux/Apache and MySQL. <br/><br/>He has been involved in a number of advanced software projects using emerging programming languages. He worked from 1999 to 2003 alongside Akvo founder Thomas Bjelkeman to build Zezame, an early AJAX-based application for web-based annotations. He has developed web applications for SEB, one of Sweden's largest banks, for Microsoft Sweden and for Gambro, a medical equipment manufacturer. Gabriel studied maths and programming at Stockholm University and physics at Sweden's Royal Institute of Technology (KTH). You can find Gabriel on Twitter at: <a href="//www.twitter.com/gabrie1">@gabrie1</a> </p></div>
<div class="extLoad" id="daniel">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/daniel240v2.png" title="Daniel Karlsson" Alt="Daniel Karlsson, web developer" /></div>
  <h1>Daniel Karlsson</h1>
  <p class="staffTitle">Web Developer</p>
 <p class="staffBio"><br/><br/> Daniel joined the Akvo team in 2008 and creates live, dazzling web pages for the Akvo system. He has been coding websites since the age of 13 and considers himself to be a full stack web craftsman and enjoys CSS, Django, HTML5 and JavaScript just as much as working on the UI or talking project process.<br/><br/> He holds a BSc in software engineering from Lund University and has an MSc in International Project Management from Chalmers University of technology and Northumbria University. He has a weak spot for simplicity, agile and lean concepts. Daniel has experience in large organisations like the Swedish Armed Forces, for which he built custom enterprise systems; he also works with small indie Mac developers. Daniel lives in Gothenburg, Sweden. Follow him on Twitter <a href="//www.twitter.com/kardan">@kardan</a>. </p></div>
<div class="extLoad" id="adrian">
  <div class="imgWrapper"> <img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/adrian240b.jpg" title="Adrian Collier" Alt="Adrian Collier, product manager, Akvo RSR" /></div>
  <h1>Adrian Collier</h1>
  <p class="staffTitle">Product manager, Akvo RSR </p>
 <p class="staffBio"><br/><br/> Adrian is responsible for the ongoing development of the Akvo Really Simple Reporting product. This includes managing the day to day activity of the Akvo RSR development team, evaluating the needs of our partners and maintaining a development plan that means the tool continues to evolve and improve. He also acts as a bridge internally between our developer and partner teams, helping to streamline the creation of new features, improvements and bug-fixes. <br/><br/>Adrian’s background is in system design, particularly in the finance and banking sector. His previous roles include head of UK Operations at ZOPA Ltd, delivery channel consultant at the Royal Bank of Scotland NV and system architect at BankToTheFuture Ltd. Most recently he worked as a business consultant and system developer at Just Us Friends Inc, a charity-backed medical centre in Tanzania. He has a BSc in Business Administration and Mathematics from Aston University. Although British, he’s based at Akvo’s headquarters in Amsterdam and speaks Dutch and Swahili.</p> </div>
<div class="extLoad" id="caetie">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Caetie240.jpg" title="Caetie Ofiesh" Alt="Caetie Ofiesh, product manager, Akvo FLOW" /></div>
  <h1>Caetie Ofiesh</h1>
  <p class="staffTitle">Product manager, Akvo FLOW</p>
 <p class="staffBio"><br/><br/> Caetie is a specialist in the design, execution and management of geospatial data collection and analysis systems. As head of program services at Gallatin Systems, she was part of the team working with Water For People on the FLOW application before Akvo took over responsibility for its ongoing development and support. <br/><br/>As well as programme management, Caetie’s expertise encompasses academic, field and applied research. She has directed research and policy studies at the US’s National Research Council and lead a baseline assessment team in Malawi collecting and analysing water and sanitation data at Water For People. Her consultancy clients include the World Bank and Urban Soccer Concepts. She has a BA in Geology from Amherst College, Massachusetts, and an MA in Geography from George Washington University. You can find Caetie on Twitter at: <a href="//www.twitter.com/caetiefish">@caetiefish</a> </p></div>
<div class="extLoad" id="rob">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/rob240.jpg" title="Rob Rochette" Alt="Rob Rochette, quality assurance" /></div>
  <h1>Rob Rochette</h1>
  <p class="staffTitle">Quality assurance </p>
 <p class="staffBio"><br/><br/> Rob leads Akvo's quality assurance process. He joined in summer 2012 from Guy’s and St Thomas’ NHS Trust, where he worked as a business analyst. Rob is an experienced Prince2-accredited programme manager and process improvement professional with an excellent track record, built on more than ten years working internationally for global technology companies such as Nokia and Motorola. <br/><br/>His passion for improving quality and business efficiency has fuelled his professional development which includes a Six Sigma Greenbelt accreditation from the membership in the American Society for Quality. Rob studied at University of Adelaide, South Australia, where he earned a BA in English Language and Literature, a BS in Mathematics and Computing and an MBA. He is based in London and recently participated in the London 2012 Olympic Games Opening Ceremony (he played one of the Brunels).</p></div>
<div class="extLoad" id="stellan">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/stellan240.jpg" title="Stellan Lagerström" Alt="Stellan Lagerström, developer" /></div>
  <h1>Stellan Lagerström</h1>
  <p class="staffTitle">Developer </p>
 <p class="staffBio"><br/><br/> Stellan is a developer, programmer and engineer who likes to work at the point where software and hardware intercept. He’s currently focused on developing Akvo FLOW, making it easier to use and more closely aligned to user needs. Until recently he was senior product engineer at the Blindsight Corporation where he created very sophisticated applications of machine vision for blind and visually impaired people.<br/><br/> Stellan first met Akvo’s Thomas Bjelkeman and Gabriel von Heijne when they studied together at the Royal Institute of Technology, Stockholm in the 1980s. Stellan stayed at the Institute as systems manager, eventually joining the team that built Astrid-2, a Swedish plasma physics research satellite. In the late 1990s he co-founded Concinnity, a maker of online business management tools and, in 1999, together with Thomas, the web development and management company Zezame. Stellan is based in Stockholm. </p></div>
<div class="extLoad" id="ivan">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/ivan.png" title="Iván Perdomo" Alt="Iván Perdomo, developer" /></div>
  <h1>Iván Perdomo</h1>
  <p class="staffTitle">Developer </p>
 <p class="staffBio"><br/><br/>ván is currently focused on development of the back-end workings of Akvo's software tools. Prior to joining Akvo, he spent five years at Openbravo where most recently he was the lead engineer for Openbravo Mobile and worked on the design and implementation of Openbravo 3. Iván has also worked as a software development contractor, system administrator and IT department head in other organisations. He is also a free/open source software user and advocate.<br/><br/>
Iván has a bachelors degree in Computer Systems Engineering from the Central American University of Technology in Honduras and a diploma in Information Technologies from the Foro Europeo, Business School of Navarra in Pamplona, Spain. He is based in Pamplona, but travels back to Honduras when possible to visit family. Follow him on Twitter <a href="//www.twitter.com/katratxo">@katratxo</a>. </p></div>
<div class="extLoad" id="lynn">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/lynn240.png" title="Lynn Greenwood" Alt="Lynn Greenwood, internal IT manager and assistant to Thomas" /></div>
  <h1>Lynn Greenwood</h1>
  <p class="staffTitle">Internal IT manager and assistant to Thomas</p>
  <p class="staffBio"><br/><br/>As well as managing our internal IT systems and supporting Thomas in his role as chief technology officer, Lynn leads our current efforts to boost the web analytics and performance data available to Akvo and its partners to continuously improve how we all work. She began her career in IT support at a distribution company in Cape Town and then London’s South Bank University.<br/><br/> In 2002 she moved to Amsterdam to take up an IT manager role at Skynet Worldwide Express, which, three years later, took her back to London for a further eight years. She loves the way technology constantly evolves and that at Akvo she’s in a position to influence and participate in developments that will have wide-reaching social benefits. South African by birth, Lynn is now based in Sweden. She speaks English, Dutch, Afrikaans and Swedish. Follow Lynn on Twitter at <a href="//www.twitter.com/lynngre">@lynngre</a> </p></div>
<div class="extLoad" id="aalt">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/aalt240.jpg" title="Aalt Leusink" Alt="Aalt Leusink, Chairman of the board" /></div>
  <h1>Aalt Leusink</h1>
  <p class="staffTitle">Chairman of the board</p>
 <p class="staffBio"><br/><br/> Aalt Leusink has a gigantic track record initiating, supervising and advising programmes that improve water resource development, drinking water supply and sanitation, environmental management and transport infrastructure. From 1981 to 1995, he was a director and consultant with IWACO, which became the Netherlands' leading consultancy in water and environmental management. He directed its Western Africa office from 1982, based in Burkina Faso. <br/><br/>From 1986 to 1995 he was director for international projects, supervising many projects in South East Asia, the Middle East and Latin America. Since then he has been an active advisor to governments, water companies, international agencies and donors in more than 30 countries. During the late 1990s he was managing director of Schiphol Management Services, responsible for the airport's multi-billion dollar overseas investments at New York JFK and Brisbane Airports. Since 2001, Aalt has initiated startup enterprises with young entrepreneurs in the water and geo-informatics sectors. He has an M.Sc in Earth Sciences from the Free University Amsterdam, where he specialised in Hydrology, Meteorology and Computer Sciences. He speaks Dutch, English, French and German and lives in the Netherlands.</p></div>
<div class="extLoad" id="markN">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/MarkN240.jpg" title="Mark Nitzberg" Alt="Mark Nitzberg, Board member" /></div>
  <h1>Mark Nitzberg</h1>
  <p class="staffTitle">Board member</p>
 <p class="staffBio"><br/><br/> Mark has been involved with Akvo as an advisor since the first meeting at Netherlands Water Partnership in Delft in 2006. He is director of Computer Vision Products at A9.com, an Amazon company, based in San Francisco.<br/><br/>Mark was co-founder and president of the <a href="//blindsight.com/">Blindsight Corporation</a>, which created computer vision technology for the blind. He was also co-founder and CTO of <a href="//www.smartleaf.com/">Smartleaf, Inc.</a>, a leader in scalable portfolio management solutions for financial firms now used for over $50 billion in assets. Mark was a principal at Viaweb, which built the first web application: a browser-based e-commerce platform, later to become Yahoo! Store. Mark has a Ph.D. in Computer Science from Harvard University.</p></div>
<div class="extLoad" id="fon">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Fon240.jpg" title="Fon Koemans" Alt="Fon Koemans, Board member" /></div>
  <h1>Fon Koemans</h1>
  <p class="staffTitle">Board member</p>
 <p class="staffBio"><br/><br/> Fon Koemans studied law in Utrecht, and completed his military duties, after which he worked for ten years at ABN Bank. In 1981 he became a board member and in 1991 chairman of The Nederlandse Waterschapsbank N.V. (NWB or Dutch Bank for Water Boards).<br/><br/> Mr Fon Koemans is also a member of the Task Force on Financing Water for All. This Task Force was formed at the end of 2005 and provided a cross-sector perspective on Innovative Financing Mechanisms for Local Actions for the World Water Forum in Mexico. </p></div>
<div class="extLoad" id="sunita">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/sunita240.jpg" title="Sunita Nadhamuni" Alt="Sunita Nadhamuni, Board member" /></div>
  <h1>Sunita Nadhamuni</h1>
  <p class="staffTitle">Board member</p>
 <p class="staffBio"><br/><br/> Sunita is director at the Center for Transformational Innovations (CeTI) at EMC, India, the world’s largest provider of data storage systems. CeTI focuses on applying innovative technology to address issues faced by emerging economies, in particular related to healthcare. She was previously founder and CEO of Arghyam, a unique and highly-regarded foundation with a mission to ensure "safe, sustainable water for all” and projects spanning 20 Indian states. She also worked in several capacities with the Asia Pacific Water Forum, building links with regional players. She brings to Akvo's board extensive experience in both grant-making and technical, research and advocacy initiatives that aim to help transform conditions for India's urban and rural poor. She is experienced in forming partnerships that connect governments, NGOs and other institutions, for impact and scale.</p><p>Between the late 1980s and 2004, Sunita lived and worked in the United States for technology companies including Sun Microsystems, Silicon Graphics, WebMD (Healtheon) and GlobeTrades Inc. From 1996 to 2004 she was an executive member of ICA Indians for Collective Action, based in Santa Clara, CA. She also helped forge cooperation between US and Indian communities through work with the American India Foundation, Rejuvenate India Movement, and founded SEVA, which supported grass-roots development work in rural India. She holds a Masters degree in Electrical and Computer Engineering from Rensselaer Polytechnic Institute in New York and a bachelors degree in Electronics and Communication from Andhra University. Based in Bangalore, Sunita is a TED India fellow and has authored two books based on her work.</p></div>
<div class="extLoad" id="becky">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/becky240.png" title="Becky Straw" Alt="Becky Straw, Board member" /></div>
  <h1>Becky Straw</h1>
  <p class="staffTitle">Board member</p>
 <p class="staffBio"><br/><br/>  Becky Straw is the Co-Founder and Chief Adventurist for The Adventure Project, a new nonprofit “adding venture” capital to support entrepreneurs in developing countries. Her and her co-founder were inspired by a passion to revolutionise giving, and create a movement to marry good intentions with measurable impact. Becky was 29-years-old when they launched.<br/>

In its first 18 months, The Adventure Project engaged 3,000 people to help create 305 jobs in India, Kenya, Uganda and Haiti. Those entrepreneurs will go on to serve over 730,000 people to better health care, food and water. The Adventure Project’s goal is to create one million jobs within ten years. <br/>

Prior to The Adventure Project, Becky spent three years helping to launch charity: water, an organisation bringing clean and safe drinking water to people in developing countries. Becky has consulted for UNICEF’s Division of Water, Sanitation and Hygiene, and graduated from Columbia University with a Master’s in International Social Welfare. She attended University of the Pacific for her undergraduate degree, and was recently awarded 2012 Young Alumni of the Year.
<br/>
    <ul>
        <li>Twitter: <a href="//www.twitter.com/beckystraw">@beckystraw</a></li>
        <li>About.me: <a href="//www.about.me/beckystraw">www.about.me/beckystraw</a></li>
        <li><a href="//www.beckystraw.com">www.beckystraw.com</a></li>
        <li><a href="//www.theadventureproject.org">www.theadventureproject.org</a></li>
    </ul>
</p>
</div>
<div class="extLoad" id="paulC">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/paulC240.png" title="Paul Ciandrini" Alt="Paul Ciandrini, Board member" /></div>
  <h1>Paul Ciandrini</h1>
  <p class="staffTitle">Board member</p>
 <p class="staffBio"><br/><br/> Paul joined Akvo USA as a charter member of the board in 2010 to help develop a strategic vision for Akvo in North America. <br/><br/>He is president and CEO of business continuity firm nScaled. Previously, he was president and CEO of HydroPoint Data Systems, Chief Risk Officer for BearingPoint Inc. and president and chief operating officer for Plumtree Software. Before Plumtree, he headed BearingPoint’s (formerly KPMG Consulting’s) international high tech practice and held senior roles at Oracle Corporation and Walker Interactive Systems. </p></div>
<div class="extLoad" id="akvoF">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/akvo240.jpg" title="Akvo foundation" Alt="Akvo foundation represented by Peter Van Der Linde" /></div>
  <h1>Akvo foundation</h1>
  <p class="staffTitle">represented by Peter Van Der Linde</p>
   </div>
<div class="extLoad" id="sam">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/Sam240.png" title="Sam Gichuru" Alt="Sam Gichuru, Board member" /></div>
  <h1>Sam Gichuru</h1>
  <p class="staffTitle">Board member</p>
Sam Gichuru is the CEO and co-founder of Nailab, one of Kenya’ s leading tech incubators. A serial entrepreneur, he is also an angel investor in promising startups and serves as an advisory board member in several early stage startups and established companies in addition to Akvo.
Sam has championed Nailab’s growth from nearly zero to an investment of over 100 million Kenyan shillings. He is currently overseeing the implementation of a million dollar government project in conjunction with the Kenya ICT board - an achievement that has seen him highlighted in local and international media including Forbes, the BBC and The Economist. Sam serves as a Rotarian and also makes a weekly appearance on Tech Tuesday, a technology and entrepreneurship themed radio show on Nairobi radio station 93.3 HopeFm.  </div>
<div class="extLoad" id="bertil">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/bertil240.jpg" title="Bertil van Vugt" Alt="Bertil van Vugt, Board member" /></div>
  <h1>Bertil van Vugt</h1>
  <p class="staffTitle">Board member</p>
 <p class="staffBio"><br/><br/> Bertil is the managing director of Africa Interactive Kenya Ltd, a subsidiary branch of the Dutch media production company where he worked from 2006 to 2011. Africa Interactive has developed a unique approach by working with a network of over 3000 local media professionals in more than 80 countries.<br/><br/> Bertil has an MSc in International Relations at the University of Amsterdam and a BA in Journalism at the Hogeschool van Utrecht. Bertil studied journalism at Ohio University in the United States as part of an exchange programme and he worked at the Cape Times newspaper in South Africa after completing his studies. You can find him on Twitter <a href="//www.twitter.com/brutuz">@brutuz</a> and he is based in Nairobi, Kenya.</p></div>
<div class="extLoad" id="stefan">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/stefan240.jpg" title="Stefan van Heukelum" Alt="Stefan van Heukelum, project officer " /></div>
  <h1>Stefan van Heukelum</h1>
  <p class="staffTitle">Finance &amp; operations officer</p>
 <p class="staffBio"><br/><br/> Akvo is growing fast and opening new offices and regional hubs in numerous locations around the world. Stefan delivers support on operational and financial processes within Akvo. He also focuses on building out our internal structures and systems in order to support this rapid development and ensure new units and employees have the operational tools and processes they need to work effectively. <br/><br/>He researches and advises the operations team on local legislation and business practices and assists in strategic planning. Stefan studied at Erasmus University, Rotterdam where he gained a degree in Business Administration and a Masters in Finance and Investment with electives in venture planning, entrepreneurial finance and private equity. He joined Akvo in April 2013. Follow Stefan on Twitter <a href="//twitter.com/SvHeukelum">@SvHeukelum</a>. </p></div>
<div class="extLoad" id="timdost">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/timdost240.jpg" title="Tim Dost" Alt=" Tim Dost, programme assistant " /></div>
  <h1>Tim Dost</h1>
  <p class="staffTitle">Programme assistant</p>
 <p class="staffBio"><br/><br/> Tim joined Akvo from the Dutch Ministry of Foreign Affairs (DGIS), where he worked to strengthen public private partnership themes such as sustainable entrepreneurship, food security, agriculture and water. In Kenya and Ethiopia he researched systems designed to help farmers increase production through improved access to information.<br/><br/> At Akvo Tim supports the collaboration with DGIS on the IATI initiative to make aid money transparent throughout the finance chain, and to make development information and results more visible to the public by scaling our efforts on project reporting and monitoring. Tim also helps extend our current partnerships and establish new relationships. Tim has a law degree and a masters in law and economics from Utrecht University, and an advanced masters in international development from Radboud University, Nijmegen. Follow Tim on Twitter <a href="//twitter.com/timdost">@timdost</a>. </p></div>
<div class="extLoad" id="winona">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/winona240.jpg" title=" Winona Azure" Alt=" Winona Azure, Akvopedia editor " /></div>
  <h1> Winona Azure</h1>
  <p class="staffTitle">Akvopedia editor </p>
 <p class="staffBio"><br/><br/> Winona is the main editor and content provider for Akvopedia, Akvo’s online resource for sharing knowledge on water and sanitation. Prior to joining Akvo in March 2011, she earned a BSc in Environmental Studies from San Francisco State University and an urban permaculture certificate. <br/><br/>Winona has initiated and participated in programmes with local, sustainable organisations, such as Green America & Global Exchange, Greywater Action, Habitat Media, the Coastal Watershed Council, and the University of California at San Francisco medical center. Winona has a BA in Writing and Literature from The California College of the Arts, which led her to teach English in South Korea, write and illustrate a graphic novella, study languages and travel to more than 14 countries. She understands how multicultural appreciation enables us to find common ground and how new learning experiences can better our lives through collaborative tools such as Akvopedia. She also volunteers in local hackathon events and civic app groups. Winona is based in Oakland, California. You can follow her on Twitter <a href="//twitter.com/noniazure">@noniazure</a>. </p></div>
<div class="extLoad" id="isha">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/isha240.jpg" title=" Isha Parihar
" Alt=" Isha Parihar, programme officer, Asia hub
" /></div>
  <h1>Isha Parihar </h1>
  <p class="staffTitle">Programme officer, Asia hub </p>
 <p class="staffBio"><br/><br/> Isha is responsible for partnership management and training on Akvo RSR and FLOW for Akvo’s Asia hub. She is the primary contact for Akvo partners in Nepal, Bangladesh and India. Isha is a sociologist by training, with a Master's in Sociology from Jamia Milia Islamia, New Delhi. Her postgraduate research analysed the history of biodiversity conservation in India, with a focus on the urban areas as newer sites of resource conflicts.<br/><br/> In 2005, Isha completed an internship in an International Honours Programme on "Rethinking Globalization" in partnership with Boston University. Isha then worked in the corporate sector for marketing research and public relations firms. Prior to joining Akvo, Isha worked as head of the Public Relations and Media wing at Global Filmbooth Ventures Pvt Ltd, a community of short film enthusiasts, bringing the fledgling and passionate short film community in India to a larger audience. Isha is a Certified Pranic Healer, having been trained on the ancient system of healing that seeks to balance energy flows in the human body. She is based in Delhi. Follow her on Twitter <a href="//twitter.com/ishaparihar">@ishaparihar</a>. </p></div>
<div class="extLoad" id="rajashi">
  <div class="imgWrapper"><img src="//akvo.org/wp-content/themes/Akvo-responsive/images/staff/rajashi240.jpg" title="  Rajashi Mukherjee

" Alt="  Rajashi Mukherjee, advisor, Asia hub

" /></div>
  <h1> Rajashi Mukherjee </h1>
  <p class="staffTitle"> Advisor, Asia hub </p>
<p class="staffBio"><br/><br/>  Rajashi joins Akvo with almost three decades experience as a monitoring and evaluation specialist in water and sanitation, public health, gender and integrated development. She plays a critical role shaping and strengthening Akvo's programmes in Asia. Before Akvo she monitored and evaluated projects for organisations such as the World Bank, Asian Development Bank (ADB), Department of Foreign and International Development (DFID), UNICEF UK, Canadian International Development Agency (CIDA) and the Government of India. <br/><br/>Rajashi has worked on assignments across India, Bangladesh, Nepal, Canada, the U.S. and Central America, including six years as Country Director, India for US-based Water For People. There, she set up the local office and executed programmes in India, one of which used Akvo FLOW for water point mapping. She holds Bachelor's and Master’s degrees in Economics from the University of Calcutta, India and an MPhil in Economics and Politics of Development from the Department of Economics, University of Cambridge, UK. Rajashi is based in Kolkata. You can find her on Twitter <a href="//twitter.com/mrajashi">@mrajashi</a>.</p> </div>
