<?php include JsonData_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>

<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-file-text-alt"></i>&nbsp;Feeds</h2>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<div id="iDivResponseContainer"></div>
		</div>
	</div>

	
	<div class="row-fluid">
<?php
if (isset($aContent['list']) && count($aContent['list']) > 0) {
?>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Feed Name</th>
					<th>slug</th>
					<th><a class="btn btn-primary btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Home::MENU_SLUG, false); ?>"><i class="icon icon-refresh"></i>&nbsp; Reload</a>
                        <a class="btn btn-success btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Feed\Add::MENU_SLUG, false); ?>"><i class="icon icon-plus"></i>&nbsp; Add</a></th>
				</tr>
			</thead>
			<tbody>
<?php
	foreach ($aContent['list'] as $mKey => $aListEntry) {

?>
				<tr>
					<td>
						<small><strong><?php echo $aListEntry['feed_name']; ?></strong></small><br>
						<?php echo $aListEntry['feed_url']; ?>
					</td>
					<td>
						<?php echo $aListEntry['feed_slug']; ?>
					</td>
					<td>
						<div class="btn-group">
							<a class="btn btn-info btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Feed\Detail::MENU_SLUG, false) . '&id=' . $aListEntry['id']; ?>"><i class="icon-file-text"></i>&nbsp; View</a>
							<a class="btn btn-warning btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Feed\Edit::MENU_SLUG, false) . '&id=' . $aListEntry['id']; ?>"><i class="icon-pencil"></i>&nbsp; Edit</a>
							<a class="btn btn-success btn-small" href="<?php echo get_bloginfo('url');?>?preview_json=<?php echo $aListEntry['feed_slug']; ?>" target="_blank"><i class="icon-eye-open"></i>&nbsp; Preview</a>
							<a class="btn btn-danger btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Feed\Remove::MENU_SLUG, false) . '&id=' . $aListEntry['id']; ?>"><i class="icon-trash"></i>&nbsp; Remove</a>
						</div>
					</td>
				</tr>
<?php

	}
?>
			</tbody>
		</table>
<?php
} else {
?>
		<div class="span12">
			 <div class="alert alert-block alert-error">There are no feeds yet.</div>
		</div>
<?php
}
?>
	</div>

	

</div>
