<?php include AkvoWvwParticipantRegistry_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">

			<div class="alert alert-error">
				<h2><i class="icon-warning-sign"></i>&nbsp;Uh-oh!</h2>
				<p>This plugin requires the <i class="icon-cogs"></i>&nbsp;<strong>KWGPress Core Plugin</strong> to work.</p>
			</div>

			<p>If you've already installed it <a href="/wp-admin/plugins.php">go activate it</a>.</p>

		</div>


	</div>

</div>