<?php include JsonData_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>
<?php
if (isset($aContent['form'])) {
$oForm = $aContent['form'];
?>
<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-pencil"></i>&nbsp;Add feed</h2>
            <p>Enter the details of the JSON feed here. </p>
			<a class="btn btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Home::MENU_SLUG, false); ?>"><i class="icon-arrow-left"></i>&nbsp; Back</a>
		</div>
	</div>

	<?php 
    echo $oForm; ?>
    
    
<?php
} else {
	if (isset($aContent['redirect'])) {
?>
<script type="text/javascript">
	var sJsonDataRedirectUrl = '<?php echo $aContent['redirect'];?>'; //it is handle by admin.js commented by asfer
</script>

<div class="container-fluid cAWPRContentWrapper">
	<div class="row-fluid">
		<div class="span6">
			<div class="alert alert-success">
				<h2><i class="icon-ok-sign"></i>&nbsp;Redirecting...</h2>
				<p>The feed has been successfully added. You will be redirected to the Feed List in 3 seconds.</p>
			</div>
		</div>
	</div>
</div>


<?php
	}
}
?>