<?php include JsonData_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>
<?php
$aDetail = $aContent['detail'];
?>
<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-file-text"></i>&nbsp;Feed Detail</h2>
			<a class="btn btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Home::MENU_SLUG, false); ?>"><i class="icon-arrow-left"></i>&nbsp; Back</a>
			<a class="btn btn-warning btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Feed\Edit::MENU_SLUG, false) . '&id=' . $aDetail['id']; ?>"><i class="icon-pencil"></i>&nbsp; Edit</a>
			<a class="btn btn-danger btn-small" href="<?php echo menu_page_url(\JsonData\Admin\Controller\Feed\Remove::MENU_SLUG, false) . '&id=' . $aDetail['id']; ?>"><i class="icon-trash"></i>&nbsp; Remove</a>
		</div>
	</div>
    <br /><br />
	<div id="iDivRegistrantDetailContainer">
		<div class="row-fluid">
			<div class="span6">
				
				<div class="row-fluid">
					<div class="span3 text-right">
						ID
					</div>
					<div class="span9">
						<?php echo $aDetail['id']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Feed Name
					</div>
					<div class="span9">
						<?php echo $aDetail['feed_name']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Feed Slug
					</div>
					<div class="span9">
						<?php echo $aDetail['feed_slug']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Feed URL
					</div>
					<div class="span9">
						<?php echo $aDetail['feed_url']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Default parameters
					</div>
					<div class="span9">
                        <?php $aParams = unserialize($aDetail['feed_parameters']); 
                        foreach ($aParams AS $key=> $val){
                            ?>
                        <?php echo $key; ?>: <?php echo $val; ?><br />
                        <?php
                        }
                        ?>
						
					</div>
				</div>
				
			</div>
			
		</div>
		<!--<hr>-->
		
		<!--<hr>-->
		
	</div>

</div>