<br /><br />
<div class="row-fluid">
<?php
if (isset($aContent['registry']) && count($aContent['registry']) > 0) {
?>
    
    <div class="tablepagination tablepagination-right">
        Totaal aantal deelnemende scholen: <?php echo $aContent['total'];?><br />
  <ul>
      <?php if($aContent['page']!=1){?>
      <li><a href="?order_by_column=<?php echo $sOrderByColumn;?>&order_by_direction=<?php echo $sOrderByDirection;?>&paging=<?php echo ($aContent['page']-1);?>">Vorige</a></li>
      <?php
      }
	for ($i=1; $i<=$aContent['pages'];$i++) {

?>
    
    <li><a href="?order_by_column=<?php echo $sOrderByColumn;?>&order_by_direction=<?php echo $sOrderByDirection;?>&paging=<?php echo $i;?>"><?php echo $i; ?></a></li>
    
    <?php }
    if($aContent['page']!=$aContent['pages']){
    ?>
    <li><a href="?order_by_column=<?php echo $sOrderByColumn;?>&order_by_direction=<?php echo $sOrderByDirection;?>&paging=<?php echo ($aContent['page']+1);?>">Volgende</a></li>
    <?php } ?>
  </ul>
</div>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
                    <?php
                    $dir = ($sOrderByColumn=='city' && $sOrderByDirection=='ASC') ? 'DESC' : 'ASC';
                    ?>
					<th><a href="?order_by_column=city&order_by_direction=<?php echo $dir;?>">Plaatsnaam, School</a></th>
					<?php
                    $dir = ($sOrderByColumn=='support_point' && $sOrderByDirection=='ASC') ? 'DESC' : 'ASC';
                    ?>
					<th><a href="?order_by_column=support_point&order_by_direction=<?php echo $dir;?>">Steunpunt</a></th>
					
					<?php
                    $dir = ($sOrderByColumn=='total_students' && $sOrderByDirection=='ASC') ? 'DESC' : 'ASC';
                    ?>
					<th><a href="?order_by_column=total_students&order_by_direction=<?php echo $dir;?>">Aantal leerlingen</a></th>
					
				</tr>
			</thead>
			<tbody>
<?php
	foreach ($aContent['registry'] as $mKey => $aRegistryEntry) {

?>
				<tr>
					<td>
						<small><strong><?php echo $aRegistryEntry['city']; ?></strong></small><br>
						<?php echo $aRegistryEntry['name']; ?>
					</td>
					
					<td><?php echo $aRegistryEntry['support_point']; ?></td>
					<td><?php echo $aRegistryEntry['total_students']; ?></td>
					
					
				</tr>
<?php

	}
?>
			</tbody>
		</table>
    <div class="tablepagination tablepagination-right">
  <ul>
      <?php if($aContent['page']!=1){?>
      <li><a href="?order_by_column=<?php echo $sOrderByColumn;?>&order_by_direction=<?php echo $sOrderByDirection;?>&paging=<?php echo ($aContent['page']-1);?>">Vorige</a></li>
      <?php
      }
	for ($i=1; $i<=$aContent['pages'];$i++) {

?>
    
    <li><a href="?order_by_column=<?php echo $sOrderByColumn;?>&order_by_direction=<?php echo $sOrderByDirection;?>&paging=<?php echo $i;?>"><?php echo $i; ?></a></li>
    
    <?php }
    if($aContent['page']!=$aContent['pages']){
    ?>
    <li><a href="?order_by_column=<?php echo $sOrderByColumn;?>&order_by_direction=<?php echo $sOrderByDirection;?>&paging=<?php echo ($aContent['page']+1);?>">Volgende</a></li>
    <?php } ?>
  </ul>
</div>
<?php
} else {
?>
		<div class="span12">
			 <div class="alert alert-block alert-error">There are no registered participants for the current batch.</div>
		</div>
<?php
}
?>
	</div>